name: LifestealAddon
version: '${project.version}'
main: eu.darkcode.sluxrecruitment.Core
api-version: '1.20'
authors: [96DarkCode96]
description: LifestealAddon for Slux
website: https://www.matejtomecek.eu
commands:
    border:
        description: "Manage world's border"
        aliases: [worldborder, wb, wborder]
        usage: "/border [set|remove] [<world>] [<size>]"
        permission: slux.developer